### PR TITLE
Remove usage of FreeNAS in filer-gateway

### PR DESCRIPTION
**Pull request by hurngchunlee**
@Jascha-N this is to remove the usage of FreeNAS in the filer-gateway code given that I am preparing for removeing the FreeNAS storage from production.  Could you please help review it?

ps. I still keep [the implementation of interfacing FreeNAS via its API](https://github.com/dccn-tg/filer-gateway/blob/master/pkg/filer/freenas.go) as it might be useful in the future.

### CODE REVIEW

**Comment by hurngchunlee** [comment]
@Jascha-N could you please help review this PR?  We plan to remove FreeNAS on next Tuesday, and this PR (and update filer-gateway) is one of the prerequisites. Thanks!

**Review by Jascha-N — APPROVED** [review]

**Review by linusband — CHANGES_REQUESTED** [review]
Freenas is still in `pkg/filer/init.go`, `pkg/filer/freenas.go` and in the README.

**Comment by hurngchunlee** [comment]
> Freenas is still in `pkg/filer/init.go`, `pkg/filer/freenas.go` and in the README.

@linusband as I mentioned in the original comment of this PR, this is intended as I will leave the code (they are just one interface implementation) and remove them in the future if FreeNAS API is really no longer needed.

**Review by linusband — APPROVED** [review]
My apologies: in that case, fire away!

**Pull request merged**
